---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "opn202"
  region: us-west-2
  version: "1.28"

nodeGroups:
  - name: ng-bottlerocket-quickstart
    instanceType: m5.2xlarge
    desiredCapacity: 3
    amiFamily: Bottlerocket
    iam:
       attachPolicyARNs:
          - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
          - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
          - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
          - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    bottlerocket:
      settings:
        kernel:
          sysctl: 
            vm.max_map_count: "262144"
