apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
  namespace: default
spec:
  general:
    serviceName: opensearch-cluster
    httpPort: 9200
    version: 2.11.0
  dashboards:
    enable: true
    version: 2.11.0
    replicas: 1
    resources:
      requests:
         memory: "2024Mi"
         cpu: "500m"
      limits:
         memory: "2024Mi"
         cpu: "500m"
  nodePools:
    - component: nodes
      replicas: 3
      diskSize: "10Gi"
      nodeSelector:
      resources:
         requests:
            memory: "4Gi"
            cpu: "500m"
         limits:
            memory: "4Gi"
            cpu: "500m"
      roles:
        - "cluster_manager"
        - "data"
      persistence:
        emptyDir: {}
